"""
Use this script to convert your csv file to mod source, so you can easily load and use it with some compile time error check.

Input:
one or more csv file
Output:
a cpp header file, and a cpp source file.
"""

import csv
import sys
import re

assert len(sys.argv) > 2, "usage: python csv2cpp.py output.hpp output.cpp input1.csv input2.csv ..."

header_strs = []
header_fmts = []

body_csv_res = []
next_csv_id = 0
body_loadcsv = []

name_filter_re = re.compile("[^a-zA-Z0-9]")

def escape_c_str(str:str):
    return str.replace("\\","\\\\").replace("\n","\\\n").replace("\r","").replace("\"","\\\"")

def to_c_var_name(str:str):
    varname = name_filter_re.sub("_", str)
    if len(varname) == 0 or varname[0].isdigit():
        varname = "_" + varname
    return varname

def handle_csv(filepath:str):
    global next_csv_id

    encoding = 'utf8'

    with open(filepath,'rb') as f:
        bts = f.read()
        bts_str = ','.join([str(x) for x in bts])
        body_csv_res.append(f"static const uint8_t res_{next_csv_id}[{len(bts)}]={'{'}{bts_str}{'}'};")
        body_loadcsv.append(f'    SSL10n::Database::PolyglotFormat::AddCSVContent((const char *)res_{next_csv_id},sizeof(res_{next_csv_id}));')
        next_csv_id += 1
        if len(bts) > 3 and bts[0] == 0xEF and bts[1] == 0xBB and bts[2] == 0xBF:
            encoding='utf-8-sig'
    with open(filepath,'r', encoding=encoding) as f:
        start = False
        for row in csv.reader(f):
            if not start:
                if len(row) > 0 and (
                    row[0] == "polyglot" or row[0] == "Polyglot" or row[0] == "BEGIN"
                ):
                    start = True
                continue
            if len(row) >= 3:
                str_part_1 = f"inline std::string {to_c_var_name(row[0])}()"
                str_part_2 = f'return SSL10n::Get("{escape_c_str(row[0])}");'
                padding_1 = max(0, 80 - len(str_part_1)) * ' '
                header_strs.append("            %s%s{%s}" %(str_part_1, padding_1, str_part_2))

                if '{' in row[2]:
                    str_part_3 = f'template <typename... Args> std::string {to_c_var_name(row[0])}(Args... format_args)'
                    str_part_4 = f'return SSL10n::FormatKeyWithDefault("{escape_c_str(row[0])}", "{escape_c_str(row[2])}", format_args...);'
                    padding_2 = max(0, 120 - len(str_part_3)) * ' '
                    header_fmts.append("            %s%s{%s}" %(str_part_3, padding_2, str_part_4))
for f in sys.argv[3:]:
    handle_csv(f)

with open(sys.argv[1], 'w', encoding='utf8') as f:
    f.write(f"""/* auto generated by sslocalization library(utils/csv2cpp.py) https://github.com/frto027/SimpleStupidLocalization */
#include "SSL10n.hpp"
#include <string>

namespace SSL10nGen {'{'}
    void LoadCsv();
    namespace STR {'{'}
{'\n'.join(header_strs)}
    {'}'} // namespace STR

    namespace FMT {'{'}
{'\n'.join(header_fmts)}
    {'}'} // namespace FMT
{'}'} // namespace SSL10nGen
""")
import pathlib
header_name = pathlib.Path(sys.argv[1]).name

with open(sys.argv[2], 'w', encoding='utf8') as f:
    f.write(f"""/* auto generated by sslocalization library(utils/csv2cpp.py) */
#include "{header_name}"

{'\n'.join(body_csv_res)}

void SSL10nGen::LoadCsv(){'{'}
{'\n'.join(body_loadcsv)}
{'}'}
""")
