import urllib.request
import csv
import io
import re

with open(r"BSManager\BSInstances\1.41.1\AssetRipperExport\Assets\Localization\Localization.bytes", "rb") as f:
    polyglot_csv_text_bts = f.read()

# polyglot_csv_text_bts = urllib.request.urlopen("https://raw.githubusercontent.com/qe201020335/PolyglotInject/refs/heads/master/assets/polyglot-inject.csv").read()

# with open("src/polyglot_csv.inl",'w') as f:
#     f.write("// this file is generated by \"scripts/update_source.py\"\n")
#     f.write(f"static uint8_t polyglot_csv[{len(polyglot_csv_text_bts)}]=")
#     f.write("{")
#     for b in polyglot_csv_text_bts:
#         f.write("%d,"%b)
#     f.write("};\n")

header_found = False

GAME_KEYS_HEADER = '''#pragma once
// clang-format off
/* 
    This file is generated by "scripts/update_source.py" from SSL10n library.
*/

namespace SSL10n {
    namespace GameKeys {
'''
GAME_KEYS_TAIL = '''
    }
}
'''

output = GAME_KEYS_HEADER

for row in csv.reader(io.StringIO(polyglot_csv_text_bts.decode("utf8"))):
    if not header_found:
        if row[0] == "Polyglot":
            header_found = True
        continue
    key = row[0]
    en_text = row[2]
    en_text_comment = en_text.replace("\\","\\\\").replace("\r","\\r").replace("\n", "\\n").replace("\"","\\\"")

    if len(key) == 0:
        continue

    c_keyname = key
    if c_keyname[0].isdigit():
        c_keyname = "_" + c_keyname
    c_keyname = c_keyname.replace("&", "_")

    c_key_align = " " * (60-len(c_keyname))
    key_align = " " * (60-len(key))
    output += f'        inline const char * {c_keyname}{c_key_align}="{key}"; {key_align}// "{en_text_comment}"\n'

output += GAME_KEYS_TAIL

with open("shared/SSL10n/GameKeys.hpp","w", encoding="utf8") as f:
    f.write(output)